name: Download grub src
on: push
jobs:
  grub_update:
    env:
      version: 2.04-32.7
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download new version
        run: |
          rm -rf *
          curl -L -O https://download.opensuse.org/repositories/Base:/System/openSUSE_Factory/src/grub2-$version.src.rpm
          rpm2cpio grub2-$version.src.rpm | cpio -idv
          rm grub2-$version.src.rpm
      - name: Setup git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit changes
        run: |
          git add .
          git commit -a -m "New version: $version"
          git tag $version
          git push
          git push origin $version
